<?php
/**
 * Magepow
 * @category Magepow
 * @copyright Copyright (c) 2014 Magepow (<https://www.magepow.com>)
 * @license <https://www.magepow.com/license-agreement.html>
 * @Author: magepow<support@magepow.com>
 * @github: <https://github.com/magepow>
 * @@Create Date: 2017-08-29 22:55:21
 * @@Modify Date: 2018-03-15 00:21:25
 * @var \Magepow\StoreLocator\Block\StoreLocator $block
 */
?>
<?php
$helper         = $this->helper('Magepow\StoreLocator\Helper\Data');
$isEnabled      = $helper->getConfigModule('general/enabled');
$page_title     = $helper->getConfigModule('general/page_title');
$identifier     = $helper->getConfigModule('general/identifier');
$descripttion   = $helper->getConfigModule('general/meta_description');
foreach ($block->getAllStores() as $key=>$store){$latitude = $store['latitude']; $longitude = $store['longitude'];}
?>
<div class="style-storelocator">
    <div class="storelocator-main                                                                                                                                                                                                                                                                                                                                                                   ">
        <div><h2>Store Location</h2></div>
        <div class="storelocator-row">
            <div class="storelocator-col">
                <div class="storelocator-search fakeimg" style="padding: 3%;">
                    <div class="map-search">
                            <input type="text" class="search-maps" id="search-maps" placeholder="search maps">
                    </div>

                    <div class="storelocator-block -search storelocator-search-radius">
                        <label class="storelocator-title" id="range_radius" for="radius">Search Radius</label>
                        <label>, km</label>
                        <div class="storelocator-wrapper">
                            <div class="storelocator-range-slider" data-storelocator-js="range-slider">
                                <div class="storelocator-handle ui-slider-handle">
                                    <div class="storelocator-tooltip">
                                        <span data-storelocator-js="radius-value" class="amount"></span>
                                        <span data-storelocator-js="radius-measurment">km</span>
                                    </div>
                                </div>
                            </div>
                            <input type="hidden" name="radius" data-storelocator-js="radius-select" value="500" min="0" max="500">
                        </div>
                        <div><button style="width: 100%;margin: 5px 0px;">Locate Nearby</button></div>
                    </div>
                    <div class="storelocator-block -filter" >
                        <div class="storelocator-filters-container">
                            <div class="storelocator-title storelocator-attribute-filter" data-storelocator-js="filters-title" >
                                <span>Filter</span><span class="storelocator-arrow" style="float: right;">v</span>
                            </div>
                            <div class="storelocator-content storelocator-hidden-filter" data-storelocator-js="filters-container" >
                                <form class="attributes" action="#" data-storelocator-js="attributes-form">
                                    <div class="storelocator-attribute-wrapper">
                                        <div class="storelocator-label">Parking Availability</div>
                                        <div class="storelocator-input">
                                            <select name="1" class="storelocator-select">
                                                <option value="" selected="">Please Select</option>
                                                <option value="0">No</option>
                                                <option value="1">Yes</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="storelocator-attribute-wrapper">
                                        <div class="storelocator-label">ATM</div>
                                        <div class="storelocator-input">
                                            <select name="2" class="storelocator-select">
                                                <option value="" selected="">Please Select</option>
                                                <option value="0">No</option>
                                                <option value="1">Yes</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="storelocator-attribute-wrapper">
                                        <div class="storelocator-label">New Arrivals</div>
                                        <div class="storelocator-input">
                                            <select name="3" class="storelocator-select storelocator_select_time" id="timer-name">
                                                <option value="" selected="">Please Select</option>
                                                    <?php foreach ($block->getAllTime() as $key=>$time):?>
                                                    <option value="<?php echo $time['time_id']?>"><?php echo $time['name']?></option>
                                                    <?php endforeach;?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="storelocator-attribute-wrapper">
                                        <div class="storelocator-label">Payment Methods</div>
                                        <div class="storelocator-input">
                                            <select name="4" class="storelocator-select" multiple="multiple" data-storelocator-js="multiple-select" style="display: none;">
                                                <option value="6">Cash</option>
                                                <option value="7">Card</option>
                                                <option value="8">PayPal</option>
                                            </select><div class="chosen-container chosen-container-multi" title="" style="width: 0px;">
                                                <ul class="chosen-choices">
                                                    <li class="search-field">
                                                        <input class="chosen-search-input default input-select-payment" type="text" autocomplete="off" value="Select Some Options" style="width: 157px;">
                                                    </li>
                                                </ul>
                                                <div class="chosen-drop">
                                                    <ul class="chosen-results"></ul>
                                                </div></div>
                                        </div>
                                    </div>
                                    <div class="storelocator-attribute-wrapper">
                                        <div class="storelocator-label">No-Contact Delivery</div>
                                        <div class="storelocator-input">
                                            <select name="9" class="storelocator-select">
                                                <option value="" selected="">Please Select</option>
                                                <option value="0">No</option>
                                                <option value="1">Yes</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="storelocator-attribute-wrapper">
                                        <div class="storelocator-label">Brands</div>
                                        <div class="storelocator-input">
                                            <div class="chosen-container chosen-container-multi" title="" style="width: 0px;">
                                                <ul class="chosen-choices" id="brand-search">
                                                    <li class="search-choise search-choise-input">
                                                    <span>A</span>
                                                        <a class="search-choice-close" data-option-array-index="0">x</a></li>
                                                    </li>
                                                    <li class="search-field">
                                                        <input class="chosen-search-input default input-select-brand" type="text" autocomplete="off" value="Select Some Options" style="width: 157px;">
                                                    </li>
                                                </ul>
                                                <div class="chosen-drop">
                                                    <ul class="chosen-results">
                                                    </ul>
                                                </div></div>
                                            <select name="8" class="storelocator-select select-options" id="select-options" multiple="multiple" data-storelocator-js="multiple-select" style="display: none;">
                                                <option value="0" class="option-select">Adidas</option>
                                                <option value="1" class="option-select">Reebok</option>
                                                <option value="2" class="option-select">Mango</option>
                                                <option value="3" class="option-select">H&amp;M</option>
                                                <option value="4" class="option-select">Collins</option>
                                            </select>
                                        </div>
                                    </div>
                                </form>
                                <div class="storelocator-actions">
                                    <button class="storelocator-button storelocator-filter-attribute" id="filter-bt" title="Filter">Filter</button>
                                    <span class="storelocator-clear" title="Reset" data-storelocator-js="clear-filters">Reset</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
               <div class="fake-storelocator" id="fake-storelocator">
                   <?php foreach ($block->getAllStores() as $key=>$store):?>
                   <?php if ($store['is_active']==1):?>
                   <div class="storelocator-store-desc" name="leftLocation" data-mapid="" data-amid="1">
                           <div class="storelocator-block blocklaong" data-latitude="<?php echo $store['latitude'] ?>" data-longitude="<?php echo $store['longitude'] ?>" data-gmap-id="<?php echo $store['gmaps_id'] ?>">
                           <div class="storelocator-image">
                               <img src="<?php echo $this->getData('mediaURL') . $store['image']; ?>" width="100%" height="100%">
                           </div>
                           <div class="storelocator-store-information">
                               <div class="storelocator-title">
                                   <a class="storelocator-link" href="#" title="Fashion Gallery" target="_blank"><?php echo $store['store_name'] ?></a></div> <br>
                               <?php echo $store['store_name']?><br>
                               Country: <?php  echo $store["country"]?> <br>
                               City: <?php echo $store['store_city']?> <br>
                               Address: <?php echo $store['address']?> <br>
                               <div style="display: none;" class="amasty_distance" id="amasty_distance_1">Distance:<span class="amasty_distance_number"></span>
                               </div>
                           </div>
                       </div>
                           <div class="storelocator-schedule-container" >
                           <div class="storelocator-today" data-storelocator-js="collapse-trigger">
                               <strong>Work Time Today:</strong>
                               <span class="storelocator-time">
                                        <span><?php echo "9:00 am - 7:00 pm"?></span>
                                        <span class="storelocator-arrow -down"></span>
                               </span>
                           </div>
                       </div>
                   </div>
                       <?php endif;?>
                   <?php endforeach;?>
               </div>
                <hr class="d-sm-none">
                </div>
                <div class="storelocator-img">
                <div id="fakeimg-googlestore"></div>
            </div>
        </div>
    </div>
</div>
<script>
    "use strict";
    var locations = <?php echo json_encode($block->getAllStores()->getData()) ?>;
    var latitude = <?php echo $latitude ?>;
    var longitude = <?php echo $longitude?>;
    function initMap(sel) {
        var map = new google.maps.Map(document.getElementById('fakeimg-googlestore'), {
            zoom: 10,
            center: new google.maps.LatLng(latitude, longitude)
        });
        var i;
        var contentString = new Array("");
        var infowindow = new google.maps.InfoWindow();
        for (i = 0; i < locations.length; i++) {
            var marker = new google.maps.Marker({
                position: new google.maps.LatLng(locations[i]['latitude'], locations[i]['longitude']),
                map: map,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            });
            contentString[i] ='<div class="storelocator-block blocklaong">'+ '<div class="storelocator-image">'+
                '<img src="'+locations[i]['image']+'" width="100%" height="100%">'+'</div>'+
                '<div class="storelocator-store-information">'+
                '<div class="storelocator-title">'+
                '<a class="storelocator-link" href="#" title="'+locations[i]["store_name"]+'" target="_blank">'+
                locations[i]['store_name']+ '</a>'+ '</div> '+'<br>'+"City"+
                locations[i]['store_city']+'<br>'+ 'Country: 11106'+ '<br>'+ '<br>'+ "Address:" + locations[i]['address']+ '<br>'+
                '<div style="display: none;" class="amasty_distance" id="amasty_distance_1">'+ "Distance:" + locations[i]['country']+
                '<span class="amasty_distance_number">'+ '</span>'+ '</div>'+ '</div>'+ '</div>';
            google.maps.event.addListener(marker, 'click', (function(marker,i) {
                return function() {
                    var content = contentString;
                    infowindow.setContent(contentString[i]);
                    infowindow.open(map, marker);
                }
            })(marker,i));
            contentString.push(marker);
        }
        var block = document.getElementById("fake-storelocator").getElementsByClassName("blocklaong");
        for (i=0; i<block.length; i++){
            block[i].addEventListener('click', function (){
                google.maps.event.trigger(contentString[this.dataset.gmapId], 'click');
            })
        }
        const mapsearch = document.getElementsByClassName('map-search');
        const input = document.getElementById("search-maps");
        map.controls[google.maps.ControlPosition.TOP_LEFT].push(mapsearch);
        const searchBox = new google.maps.places.SearchBox(input);
        map.addListener("bounds_changed", () => {
            searchBox.setBounds(map.getBounds());
        });
        let markers = [];
        searchBox.addListener("places_changed", () => {
            const places = searchBox.getPlaces();
            if (places.length == 0) { return;}
            markers.forEach(marker => {
                marker.setMap(null);
            });
            markers = [];
            const bounds = new google.maps.LatLngBounds();
            places.forEach(place => {
                if (!place.geometry) { return;}
                const icon = {
                    url: place.icon,
                    size: new google.maps.Size(71, 71),
                    origin: new google.maps.Point(0, 0),
                    anchor: new google.maps.Point(17, 34),
                    scaledSize: new google.maps.Size(25, 25)
                };
                markers.push(
                    new google.maps.Marker({
                        map,
                        icon,
                        title: place.name,
                        position: place.geometry.location
                    })
                );
                if (place.geometry.viewport) {
                    bounds.union(place.geometry.viewport);
                } else {
                    bounds.extend(place.geometry.location);
                }
            });
            map.fitBounds(bounds);
        });
    }
</script>
<?php if(true): ?>
    <script>
        require(['jquery', 'googlestorelocator'], function ($ ,myJquery) {
            myJquery();
        });
    </script>
<?php endif;?>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=&callback=initMap&libraries=places&v=weekly"></script>
